services:
  postgres:
    image: postgres:13.11-bullseye
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

  redis:
    image: redis:7.0.12-alpine
    container_name: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass "secret"
    tmpfs: /data
    ports:
      - 6379:6379
    networks:
      - backend-network
      
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: always
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - backend-network

volumes:
  postgres-data:
  redis-data:
  whisper-data:

networks:
  backend-network:
    name: backend-network
    driver: bridge
